name: "Pull Request Docs Check"
on:
  pull_request:


jobs:
  check-build:
    runs-on: ubuntu-latest
    steps:
    - uses: ros-controls/control.ros.org-deployment-scripts@master
      with:
        install_extensions: false
